name: udacity-ai-env
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py314hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - decorator=5.2.1=py314hca03da5_0
  - executing=2.2.1=py314hca03da5_0
  - expat=2.7.3=h982b769_0
  - ipython=9.7.0=py314hca03da5_0
  - ipython_pygments_lexers=1.1.1=py314hca03da5_0
  - jedi=0.19.2=py314hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.2.1=py314hca03da5_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - parso=0.8.5=py314hca03da5_0
  - pexpect=4.9.0=py314hca03da5_1
  - pip=25.2=pyh0d26453_1
  - prompt-toolkit=3.0.52=py314hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py314hca03da5_0
  - pygments=2.19.1=py314hca03da5_0
  - python=3.14.0=h1858270_101_cp314
  - python_abi=3.14=1_cp314
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py314hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - traitlets=5.14.3=py314hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/udacity-ai-env
